name: Delete workflow runs
on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days to keep runs'
        required: true
        default: '30'
      minimum_runs:
        description: 'The minimum number of runs to keep for each workflow'
        required: true
        default: '6'
jobs:
  delete:
    name: Delete
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days }}
          keep_minimum_runs: ${{ github.event.inputs.minimum_runs }}