name: Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://devgio.xyz
    # Default parameters
    defaults:
      # For steps using 'run'
      run:
        working-directory: deployment/terraform
    steps:
      - name: Setup environment
        run: |
          echo "DEPLOYMENT_ID=deployment-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
        working-directory: /
      - name: Load source code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate
      - name: Terraform Apply
        id: apply
        # The 'target' flag used below is an exceptional case, because of a shortcoming of
        # the 'service-accounts' module. We have to generate the random ID separately, before
        # creating the other resources. See:
        # https://github.com/terraform-google-modules/terraform-google-service-accounts/issues/46#issuecomment-895773725
        run: |
          terraform apply -auto-approve -target=random_id.project_id
          terraform apply -auto-approve
      - name: Add mask for sensitive output of Terraform Apply
        # Hides the given value from workflow logs, even if it is not set as a secret
        run: |
          echo "::add-mask::$(terraform output -raw gcp_creds)"
      - name: Extract output of Terraform Apply
        run: |
          echo "PROJECT_ID=$(terraform output -raw project_id)" >> $GITHUB_ENV
          echo "INSTANCE_NAME=$(terraform output -raw instance_name)" >> $GITHUB_ENV
          echo "COMPUTE_ZONE=$(terraform output -raw compute_zone)" >> $GITHUB_ENV
          echo "GCP_CREDS=$(terraform output -raw gcp_creds)" >> $GITHUB_ENV
      - name: Copy source code
        uses: actions-hub/gcloud@master
        env:
          APPLICATION_CREDENTIALS: ${{ env.GCP_CREDS }}
          CLOUDSDK_COMPUTE_ZONE: ${{ env.COMPUTE_ZONE }}
          # The env variable PROJECT_ID is set by the step above
        with:
          args: >
            compute scp ${GITHUB_WORKSPACE}/ ${{ env.INSTANCE_NAME }}:~/${{ env.DEPLOYMENT_ID }}
            --recurse --compress
      - name: Build and start
        uses: actions-hub/gcloud@master
        env:
          CLOUDSDK_COMPUTE_ZONE: ${{ env.COMPUTE_ZONE }}
          # PROJECT_ID is set by the step above
          # APPLICATION_CREDENTIALS is set by the first step using gcloud
        with:
          # 1. ssh into the instance
          # 2. export GitHub secrets as env vars
          # 3. run the startup script
          args: >
            compute ssh ${{ env.INSTANCE_NAME }} --command
            './${{ env.DEPLOYMENT_ID }}/deployment/startup.sh
            "${{ secrets.TOR_PRIVATE_KEY }}"
            ${{ env.DEPLOYMENT_ID }}/docker-compose.prod.yml'