name: Verification
on:
  pull_request:
    branches:
      - development
jobs:
  quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - name: Load source code
        uses: actions/checkout@v2
      - name: Evaluate code quality
        uses: ./.github/workflows/actionQuality
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Load source code
        uses: actions/checkout@v2
      - name: Prepare Node.js
        uses: ./.github/workflows/actionPrepareNode
      - name: Build
        run: yarn build
